### ISSUE TITLE
Allow using existing github restrictions

### ISSUE THREAD

**Issue by ccatlett2000** [Mergifyio/mergify-engine#141]
It would be great if it was possible to configure mergify to use existing github configurtions. I already use github's own protected branch system to prevent merging before CI/CD tests pass/approval/etc, and I don't want to configure that in two places. Basically, I just want mergify to press the green merge button as soon as it's available.

**Comment by sileht** [comment]
Hi,
You don't need to configure it both, Mergify leverages the Github branch protection system.
So you put in .mergify.yml you branches settings, and Merfigy uses Github API to configure the Github branch protection system.

We don't plan to do the other way, because we plan to provide a fine-grained configuration of the branch settings, like different branch settings depending on some criteria (Pull metadata/owner/...).

**Comment by ccatlett2000** [comment]
Is it possible to configure mergify to require signed commits? I have certain high-risk repos that currently use that feature.

**Comment by sileht** [comment]
Github API does not yet support do configure this setting, but as soon this new feature is avialable via API. We should adding it.

**Comment by ccatlett2000** [comment]
Ok, thanks for all the help

**Comment by gmartinez-anchor** [comment]
> Is it possible to configure mergify to require signed commits? I have certain high-risk repos that currently use that feature.

This is now supported but silently enforced by Github. Would be great to add a message in the PR if a commit isn't signed.
