### ISSUE TITLE
@Mergify rebase runs slow and finally fails with F7978

### ISSUE THREAD

**Issue by blindpirate** [Mergifyio/mergify-engine#1588]
### Context

Take this PR as an example: https://github.com/gradle/gradle/pull/14818#issuecomment-730095499

It takes Mergify ~30 minutes to perform the rebase action. And it finally failed with no reason, only a error code `F7978`. What shall I do now?

**Comment by blindpirate** [comment]
In another PR, it succeeded, but took ~5 minutes, is this normal? https://github.com/gradle/gradle/pull/14862

**Comment by jd** [comment]
There are multiple problems here, so let me try to recap.
1. Multiple rebase were triggered on that repo, and Mergify only handles one task at a time. A rebase in particular is being retried by Mergify over and over again. That's why you saw delays.
2. The retried rebase is not rebase-able because the PR author did not give permission for the repository maintainer to push to its branch, which means Mergify is unable to force-push the rebase after the rebase. Mergify should report an error for that rather than retrying for ever. The fix for that is https://github.com/Mergifyio/mergify-engine/pull/1589

**Comment by blindpirate** [comment]
Thanks for the quick response. 

However, I think the contributor did give repo maintainer push access, as I manually force-pushed after the mergify rebase action failed:

![image](https://user-images.githubusercontent.com/12689835/99744008-d00ec780-2b11-11eb-8aee-73ef20c88b3b.png)

**Comment by jd** [comment]
For https://github.com/gradle/gradle/pull/14862 I dug and found another issue. The operation took a lot of time and the git process was killed during the operation (likely due to a restart of the engine). The engine should have retried but it just gave up thinking git failed the merge (whereas it was killed by system shutdown).
We're working on a fix.

**Comment by jd** [comment]
Fixed by https://github.com/Mergifyio/mergify-engine/pull/1592
