### ISSUE TITLE
A pull request was merged before the required checks passed

### ISSUE THREAD

**Issue by bowlofeggs** [Mergifyio/mergify-engine#347]
Greetings!

I just noticed a pull request on my project that got merged by mergify before the tests passed:

https://github.com/fedora-infra/bodhi/pull/2992

Here is a link to my mergify rules that were in place when the merge happened:

https://github.com/fedora-infra/bodhi/blob/1077c618dae5b29d1b178a8c71a14584e6503c8c/.mergify.yml

If you look at the checks tab on that pull request, you can see that none of the CI jobs (except for DCO bot) had reported success:

https://github.com/fedora-infra/bodhi/pull/2992/checks?check_run_id=62922690

It should have waited for all the required CI tests to report success before merging. Also, it seems odd that the other two Mergify checks on there report "cancelled" as their status, even though the merge happened.

Any ideas what might have happened? I've not seen it do this before.

**Comment by sileht** [comment]
The PR was mergeable at some point in time as we can see in the previous check suite:
https://github.com/fedora-infra/bodhi/pull/2992/checks?check_run_id=62749895

We have a kind of race when two rules asks Mergify to merge the PR.

The first rule try to merge the PR, this one is not up2date, so because strict=true, the PR is updated.
Then the second rule is evaluated, and everything matches, but now the PR is up2date now, so the PR is merged.

I will add some double check on the head sha to prevent this.
