### ISSUE TITLE
Conflict condition

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#449]
Would it be possible to add a boolean attribute of whether there are merge conflicts in a PR? That could be used to add certain reviewers or assignees, for example.

**Comment by sileht** [comment]
I think we can easily expose this. Github API have an attribute called mergeable_state that can take the value "conflict". We don't want to expose this attribute directly because it's a complicated beast (and some state have some issue).

Exposing a boolean when this field is set to "conflict" looks good to me.
