### ISSUE TITLE
GitHub required checks bugged

### ISSUE THREAD

**Issue by thislooksfun** [Mergifyio/mergify-engine#541]
The support for GitHub's required checks (#487) seems not fully implemented. https://github.com/thislooksfun/earthdawn/pull/105 didn't automatically merge because [the check](https://github.com/thislooksfun/earthdawn/runs/317044524) failed, though I'm not sure why that was.

**Comment by jd** [comment]
Can you share your GitHub branch protection settings?

**Comment by thislooksfun** [comment]
Certainly! 
<img width="555" alt="Screen Shot 2019-11-26 at 4 20 31 PM" src="https://user-images.githubusercontent.com/5367333/69677490-b656b380-1068-11ea-840c-a4e1fbb3dac2.png">

**Comment by thislooksfun** [comment]
Any progress on this? I am running into this issue fairly regularly, and it's definitely slowing down my merge process.

**Comment by sileht** [comment]
Do you have a more recent pull request with the issue ? 

Because It looks like this PR have been handled first by the bugged code
(the merge check have a conclusion set to "failure" which was occurring before we fix the issue)

And then Mergify update the PR with the fixed code, but since GitHub returns "failure" even we set it back to "in_progress". This GitHub weird behavior have lost Mergify about the expected PR state, that why Mergify didn't take action to merge the PR.

**Comment by thislooksfun** [comment]
Certainly, here is one I just created: https://github.com/thislooksfun/earthdawn/pull/152

**Comment by sileht** [comment]
Erf, Ok I see what happen, another wrong value reported by Github for mergeable_state...
