### ISSUE TITLE
Mergify is claiming ownership of all commits

### ISSUE THREAD

**Issue by ocharles** [Mergifyio/mergify-engine#764]
See:

![image](https://user-images.githubusercontent.com/20878/75965887-5d958300-5ec1-11ea-8007-f942bbcde092.png)

All of these commits have been created by Mergify, but recently all commits started being attributed to Mergify, not the author who created the PR.

**Comment by sileht** [comment]
I was answering your email, but I will retry here instead.

We didn't change anything on how thing are merged, Mergify just click on the merge Button with your selected option, the merge itself is done by Github.

So Github may have changed something, we are currently looking at it.

**Comment by ocharles** [comment]
Oh, thanks @sileht! I wasn't sure where best to raise the issue, let's continue here, so the rest of the team can follow along :+1:

**Comment by sileht** [comment]
I took a look at random run of our integration tests:

In december we having the expected behavior (Mergify (mergify-test here) is only the committer):
* https://github.com/mergifyio-testing/repo-08bf934b-17fa-4d24-aa5c-c38edbc366aa-test_backport_squash_and_merge/commit/7b68d743cde41fd19cd3f2e68a0e07382238c21c
* https://api.github.com/repos/mergifyio-testing/repo-08bf934b-17fa-4d24-aa5c-c38edbc366aa-test_backport_squash_and_merge/commits/7b68d743cde41fd19cd3f2e68a0e07382238c21c

Last week, we see the committer has change to `Github` and the UI don't show it, but we see it in the API:
* https://github.com/mergifyio-testing/repo-16e8a92f-6bcf-4a5d-b908-4f0562261bfa-test_backport_squash_and_merge/commit/ea1af8cc627dfc6c475383be07716558165967b2
* https://api.github.com/repos/mergifyio-testing/repo-16e8a92f-6bcf-4a5d-b908-4f0562261bfa-test_backport_squash_and_merge/commits/ea1af8cc627dfc6c475383be07716558165967b2

I just rerun this test, and now we see the committer is still `Github` and the author has become `Mergify bot`
* https://github.com/mergifyio-testing/repo-b4cf5add-7829-41ef-bcbf-55679b27271f-test_backport_squash_and_merge/commit/ef110f5e5a163fbd84e1de0ef9b1744331bcb0f3
* https://api.github.com/repos/mergifyio-testing/repo-b4cf5add-7829-41ef-bcbf-55679b27271f-test_backport_squash_and_merge/commits/ef110f5e5a163fbd84e1de0ef9b1744331bcb0f3

Really looks like Github change the author and committer of "squash+merge" to something weird.

**Comment by sileht** [comment]
I contacted the Github support has the behavior change is come from their side. I will update the issue when I got some answer.

**Comment by ocharles** [comment]
Thank you! Hopefully just a small oversight on their side.

**Comment by sileht** [comment]
Looks like they fix the issue:

> From GH:
> Thanks for reaching out and reporting this. I believe this is related to a recent change on our end which the team fixed after you reached out.

**Comment by sileht** [comment]
Can you confirm ?

**Comment by ocharles** [comment]
Yep, everything is back to normal now. Thank you!
