### ISSUE TITLE
backport action reports wrong status

### ISSUE THREAD

**Issue by dsavineau** [Mergifyio/mergify-engine#956]
When backporting a PR on multiple branches and one of the backport fails then all backport status are set to failed even if the other backports went well.

You can see an exemple at https://github.com/ceph/ceph-ansible/pull/5262/checks

Both stable-5.0 and stable-4.0 BP are ok but not stable-3.2 BP due to a conflict. But the check status on stable-5.0 and stable-4.0 is failed with the message `No backport have been created - Backport to branch stable-5.0 failed` and the BP PR is actually created successfully

**Comment by jd** [comment]
It looks like the engine failed to retrieve the backport it has created which are indeed visible:
- https://github.com/ceph/ceph-ansible/pull/5285
- https://github.com/ceph/ceph-ansible/pull/5286

That's right?

**Comment by dsavineau** [comment]
Yep that's right

**Comment by jd** [comment]
Alright. This is due to a race condition in the way the engine treats the events; it started doing the backport for this PR twice at the same time:
- the first attempt succeeded
- the second one failed and override the first one check result

This should be fixed with the ongoing work we have in #943

**Comment by jd** [comment]
This should be fixed now that events are batched.
